/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import com.mycompany.tpv.Panel;

/**
 *
 * @author Equipo
 */
public class Categoria extends javax.swing.JPanel {

    /**
     * Creates new form categoría
     */
    public Categoria(String nombre) {
        initComponents();
        jLabel1.setText(nombre);
        this.setName(nombre);
        
        // ═══════════════════════════════════════════════════════════════
        // COLORES PROFESIONALES PARA CATEGORÍA
        // ═══════════════════════════════════════════════════════════════
        this.setBackground(new java.awt.Color(59, 130, 246));  // Azul moderno
        this.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(37, 99, 235), 2));  // Borde azul oscuro
        
        jLabel1.setForeground(java.awt.Color.WHITE);  // Texto blanco
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        
        // Agregar efecto hover
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            private boolean yaRegistrado = false;
            
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (!yaRegistrado) {
                    jLabel1MouseClicked(evt);
                }
            }
            
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setBackground(new java.awt.Color(37, 99, 235));  // Azul más oscuro en hover
                setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                yaRegistrado = true;
            }
            
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setBackground(new java.awt.Color(59, 130, 246));  // Volver al azul original
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 51));
        setMaximumSize(new java.awt.Dimension(130, 130));
        setMinimumSize(new java.awt.Dimension(130, 130));
        setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 130));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 130));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        String cat = jLabel1.getText();
        Panel.categoriaActual = this.getName();
        System.out.println("La categoria seleccionada es: " +  Panel.categoriaActual);
        for (int i = 0; i < Panel.jPanel6.getComponentCount(); i++) {
            if (Panel.jPanel6.getComponent(i) instanceof PanelCategoria) {
                PanelCategoria pc = (PanelCategoria) Panel.jPanel6.getComponent(i);
                if (pc.getName() != null && pc.getName().equals(Panel.categoriaActual)) {
                    pc.setVisible(true);
                } else {
                    pc.setVisible(false);
                }
            }
        }
        Panel.jPanel6.revalidate();
        Panel.jPanel6.repaint();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}