/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import com.mycompany.tpv.Panel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Equipo
 */
public class Producto extends javax.swing.JPanel {

    /**
     * Creates new form Producto
     */
    public int cantidad = 1;
    private String nombreProducto;  // Guardamos el nombre para usarlo en el tooltip
    
    public Producto(String nombre, float precio) {
        initComponents();
        this.nombreProducto = nombre;
        
        // ═══════════════════════════════════════════════════════════════
        // COLORES PROFESIONALES
        // ═══════════════════════════════════════════════════════════════
        this.setBackground(new java.awt.Color(249, 250, 251));  // Gris muy claro
        this.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(229, 231, 235), 1));  // Borde gris suave
        
        // ── CAMBIO: jLabel1 ya no muestra el nombre, solo la imagen ──────────
        // El nombre se muestra como tooltip al pasar el ratón
        this.jLabel1.setText("");  // Vacío por defecto (se llenará con imagen si hay)
        this.jLabel1.setToolTipText(nombre);  // Tooltip con el nombre
        this.jLabel1.setBackground(java.awt.Color.WHITE);
        this.jLabel1.setOpaque(true);
        
        this.jLabel2.setText(precio + " €");
        this.jLabel2.setForeground(new java.awt.Color(16, 185, 129));  // Verde profesional
        this.jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        
        // ── CAMBIO: MouseListener solo en jLabel1 (la imagen), no en todo el panel ──────
        this.jLabel1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (existe(nombre)) {
                    // Actualizar cantidad y total de producto existente
                    for (int i = 0; i < Panel.jTable1.getRowCount(); i++) {
                        if (Panel.modelo.getValueAt(i, 1).equals(nombre)) {
                            cantidad = Integer.parseInt(Panel.jTable1.getValueAt(i, 0).toString()) + 1;
                            Panel.modelo.setValueAt(cantidad, i, 0);
                            Panel.modelo.setValueAt(cantidad * precio, i, 3);
                            break;
                        }
                    }
                } else {
                    Panel.modelo.addRow(new Object[]{cantidad, nombre, precio, cantidad * precio});
                }

                // Calcular total
                double total = 0;
                for (int i = 0; i < Panel.jTable1.getRowCount(); i++) {
                    total += Double.parseDouble(Panel.jTable1.getValueAt(i, 3).toString());
                }
                Panel.jLabel2.setText(String.format("%.2f", total));

                Panel.jPanel3.revalidate();
                Panel.jPanel3.repaint();
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                jLabel1.setBackground(new java.awt.Color(243, 244, 246));
                jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                jLabel1.setBackground(java.awt.Color.WHITE);
            }
        });
    }
    
    public boolean existe(String nombre){
        for (int i = 0; i < Panel.modelo.getRowCount(); i++){
            if (Panel.modelo.getValueAt(i, 1).equals(nombre)){
                return true;
            }
        }
        return false;
    }
    
    /**
     * Devuelve el nombre del producto (útil para eliminarlo después)
     */
    public String getNombreProducto() {
        return nombreProducto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(150, 150));
        setMinimumSize(new java.awt.Dimension(150, 150));
        setPreferredSize(new java.awt.Dimension(150, 150));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(60, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 50));
        add(jLabel1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 50));
        add(jLabel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
