/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.tpv;

import componentes.PanelCategoria;
import componentes.Categoria;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.Random;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo
 */
public class formulario extends javax.swing.JDialog {
    private Random rd = new Random();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formulario.class.getName());

    /**
     * Creates new form formulario
     */
    public formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        aplicarEstiloProfesional();
    }
    
    /**
     * Aplica un estilo moderno y profesional al formulario
     */
    private void aplicarEstiloProfesional() {
        // Colores profesionales
        java.awt.Color azulOscuro = new java.awt.Color(31, 41, 55);
        java.awt.Color verdeAcento = new java.awt.Color(16, 185, 129);
        java.awt.Color rojoError = new java.awt.Color(239, 68, 68);
        java.awt.Color grisClaro = new java.awt.Color(243, 244, 246);
        java.awt.Color blancoTexto = new java.awt.Color(255, 255, 255);
        java.awt.Color textoOscuro = new java.awt.Color(17, 24, 39);
        
        // Fondo del panel
        jPanel1.setBackground(grisClaro);
        
        // Estilizar label
        jLabel1.setText("Categoría");
        jLabel1.setForeground(textoOscuro);
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        
        // Estilizar campo de texto
        jTextField1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219), 1),
            javax.swing.BorderFactory.createEmptyBorder(10, 12, 10, 12)
        ));
        
        // Estilizar botones
        estilizarBoton(jButton1, verdeAcento, blancoTexto, "Crear");
        estilizarBoton(jButton2, rojoError, blancoTexto, "Borrar");
    }
    
    /**
     * Aplica un estilo consistente a un botón
     */
    private void estilizarBoton(javax.swing.JButton boton, java.awt.Color fondo, java.awt.Color texto, String nuevoTexto) {
        boton.setText(nuevoTexto);
        boton.setBackground(fondo);
        boton.setForeground(texto);
        boton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        boton.setFocusPainted(false);
        boton.setBorderPainted(false);
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton.setPreferredSize(new java.awt.Dimension(100, 35));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("categoría");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String nombreCategoria = jTextField1.getText().trim();
        
        // Validar que no esté vacío
        if (nombreCategoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, escribe un nombre para la categoría", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validar que no exista ya
        for (Categoria cat : categoriaxml.categorias) {
            if (cat.getName().equals(nombreCategoria)) {
                JOptionPane.showMessageDialog(this, "Esta categoría ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
   
        Categoria cat = new Categoria(nombreCategoria);
        cat.jLabel1.setText(nombreCategoria);
        cat.setName(nombreCategoria);
        Panel.jPanel7.add(cat);
        categoriaxml.categorias.add(cat);
        categoriaxml.guardarCategorias();
        Panel.categoriaActual = cat.getName();
        System.out.println("Tu categoria actual es " + Panel.categoriaActual);
        Panel.jPanel7.revalidate();
        Panel.jPanel7.repaint();

        Panel.jPanel7.add(Box.createRigidArea(new Dimension(0, 10)));

        PanelCategoria pc = new PanelCategoria();
        Panel.jPanel6.add(pc);
        pc.setName(nombreCategoria);
        Panel.jPanel6.revalidate();
        Panel.jPanel6.repaint();
        Panel.jPanel6.setComponentZOrder(pc, 0);
        Random random = new Random();
        pc.jPanel2.setBackground(new Color(random.nextInt(255), random.nextInt(255), random.nextInt(255)));
        Panel.jPanel6.setComponentZOrder(pc, 0);
        for (int i = 0; i < Panel.jPanel6.getComponentCount(); i++) {
            if (Panel.jPanel6.getComponent(i) instanceof PanelCategoria) {
                PanelCategoria panelCat = (PanelCategoria) Panel.jPanel6.getComponent(i);
                if (panelCat.getName() != null && panelCat.getName().equals(Panel.categoriaActual)) {
                    panelCat.setVisible(true);
                } else {
                    panelCat.setVisible(false);
                }
            }
        }
        
        JOptionPane.showMessageDialog(this, "Categoría creada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        jTextField1.setText("");
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Botón BORRAR Categoria
        String nombreCategoria = jTextField1.getText().trim();
        
        // Validar que no esté vacío
        if (nombreCategoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, escribe el nombre de la categoría a borrar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Buscar la Categoria
        Categoria categoriaABorrar = null;
        for (Categoria cat : categoriaxml.categorias) {
            if (cat.getName().equals(nombreCategoria)) {
                categoriaABorrar = cat;
                break;
            }
        }
        
        if (categoriaABorrar == null) {
            JOptionPane.showMessageDialog(this, "La categoría '" + nombreCategoria + "' no existe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirmar antes de borrar
        int respuesta = JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que quieres borrar la categoría '" + nombreCategoria + "'?\nSe borrarán también todos sus productos.",
            "Confirmar borrado",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if (respuesta == JOptionPane.YES_OPTION) {
            // Borrar de la lista de categorías
            categoriaxml.categorias.remove(categoriaABorrar);
            
            // Borrar del panel visual (jPanel7)
            Panel.jPanel7.remove(categoriaABorrar);
            
            // Borrar el PanelCategoria correspondiente de jPanel6
            Component[] componentes = Panel.jPanel6.getComponents();
            for (Component comp : componentes) {
                if (comp instanceof PanelCategoria) {
                    PanelCategoria pc = (PanelCategoria) comp;
                    if (pc.getName() != null && pc.getName().equals(nombreCategoria)) {
                        Panel.jPanel6.remove(pc);
                        break;
                    }
                }
            }
            
            // Borrar productos de esa Categoria del XML
            if (productoxml.productosPorCategoria.containsKey(nombreCategoria)) {
                productoxml.productosPorCategoria.remove(nombreCategoria);
                productoxml.guardarProductos();
            }
            
            // Guardar cambios en categorías
            categoriaxml.guardarCategorias();
            
            // Si era la Categoria actual, limpiar
            if (Panel.categoriaActual != null && Panel.categoriaActual.equals(nombreCategoria)) {
                Panel.categoriaActual = null;
            }
            
            // Actualizar la interfaz
            Panel.jPanel7.revalidate();
            Panel.jPanel7.repaint();
            Panel.jPanel6.revalidate();
            Panel.jPanel6.repaint();
            
            JOptionPane.showMessageDialog(this, "Categoría '" + nombreCategoria + "' borrada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            jTextField1.setText("");
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                formulario dialog = new formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
