/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.tpv;

import static com.mycompany.tpv.Panel.jPanel6;
import componentes.PanelCategoria;
import componentes.Producto;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo
 */
public class FormularioProducto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioProducto.class.getName());
    private String rutaImagenSeleccionada = null;

    /**
     * Creates new form FormularioProducto
     */
    public FormularioProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        aplicarEstiloProfesional();
    }
    
    /**
     * Aplica un estilo moderno y profesional al formulario
     */
    private void aplicarEstiloProfesional() {
        // Colores profesionales
        java.awt.Color azulOscuro = new java.awt.Color(31, 41, 55);
        java.awt.Color azulMedio = new java.awt.Color(55, 65, 81);
        java.awt.Color verdeAcento = new java.awt.Color(16, 185, 129);
        java.awt.Color rojoError = new java.awt.Color(239, 68, 68);
        java.awt.Color grisClaro = new java.awt.Color(243, 244, 246);
        java.awt.Color blancoTexto = new java.awt.Color(255, 255, 255);
        java.awt.Color textoOscuro = new java.awt.Color(17, 24, 39);
        
        // Fondo del panel
        jPanel1.setBackground(grisClaro);
        
        // Estilizar labels
        java.awt.Font fuenteLabel = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 15);
        jLabel1.setText("Producto");
        jLabel1.setForeground(textoOscuro);
        jLabel1.setFont(fuenteLabel);
        jLabel2.setForeground(textoOscuro);
        jLabel2.setFont(fuenteLabel);
        jLabel3.setText("Precio");
        jLabel3.setForeground(textoOscuro);
        jLabel3.setFont(fuenteLabel);
        
        // Estilizar campos de texto
        java.awt.Font fuenteCampo = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14);
        javax.swing.border.Border bordeCampo = javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(209, 213, 219), 1),
            javax.swing.BorderFactory.createEmptyBorder(10, 12, 10, 12)
        );
        
        jTextField1.setFont(fuenteCampo);
        jTextField1.setBorder(bordeCampo);
        jTextField2.setFont(fuenteCampo);
        jTextField2.setBorder(bordeCampo);
        
        // Estilizar botones
        estilizarBoton(jButton1, verdeAcento, blancoTexto, "Crear");
        estilizarBoton(jButton2, azulMedio, blancoTexto, "Seleccionar Imagen");
        estilizarBoton(jButton3, rojoError, blancoTexto, "Borrar");
    }
    
    /**
     * Aplica un estilo consistente a un botón
     */
    private void estilizarBoton(javax.swing.JButton boton, java.awt.Color fondo, java.awt.Color texto, String nuevoTexto) {
        boton.setText(nuevoTexto);
        boton.setBackground(fondo);
        boton.setForeground(texto);
        boton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        boton.setFocusPainted(false);
        boton.setBorderPainted(false);
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("producto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Imagen");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("precio");

        jButton2.setText("Seleccionar imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Botón CREAR producto
        String nombreProducto = jTextField1.getText().trim();
        String precioTexto = jTextField2.getText().trim();
        
        // Validar campos
        if (nombreProducto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, escribe el nombre del producto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (precioTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, escribe el precio del producto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        float precioProducto;
        try {
            precioProducto = Float.parseFloat(precioTexto);
            if (precioProducto <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor que 0", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Producto p = new Producto(nombreProducto, precioProducto);
        
        // Copiar imagen a carpeta local si se seleccionó una
        String rutaImagenRelativa = "";
        if (rutaImagenSeleccionada != null && !rutaImagenSeleccionada.isEmpty()) {
            rutaImagenRelativa = productoxml.copiarImagenLocal(rutaImagenSeleccionada);
            
            if (!rutaImagenRelativa.isEmpty()) {
                try {
                    String rutaCompleta = productoxml.obtenerRutaAbsoluta(rutaImagenRelativa);
                    ImageIcon imagen = new ImageIcon(rutaCompleta);
                    // Usar tamaño fijo en vez de getWidth/getHeight que pueden ser 0
                    Image imagenEscalada = imagen.getImage().getScaledInstance(
                            120,  // Ancho fijo
                            100,  // Alto fijo
                            Image.SCALE_SMOOTH
                    );
                    p.jLabel1.setIcon(new ImageIcon(imagenEscalada));
                    p.jLabel1.setText("");
                } catch (Exception e) {
                    System.err.println("Error al cargar imagen: " + e.getMessage());
                }
            }
        }
        
        // Añadir el producto al panel visible
        boolean productoAñadido = false;
        for (int i = 0; i < Panel.jPanel6.getComponentCount(); i++){
            if (Panel.jPanel6.getComponent(i).isVisible()){
                PanelCategoria pc = (PanelCategoria) Panel.jPanel6.getComponent(i);
                pc.jPanel1.add(p);
                
                // Guardar el producto en la estructura de datos
                String categoriaActual = pc.getName();
                if (!productoxml.productosPorCategoria.containsKey(categoriaActual)) {
                    productoxml.productosPorCategoria.put(categoriaActual, new ArrayList<>());
                }
                // Guardar ruta relativa en vez de absoluta
                productoxml.ProductoData prodData = new productoxml.ProductoData(
                    nombreProducto, 
                    precioProducto, 
                    rutaImagenRelativa
                );
                productoxml.productosPorCategoria.get(categoriaActual).add(prodData);
                
                // Guardar en XML
                productoxml.guardarProductos();
                productoAñadido = true;
            }
        }
        
        if (!productoAñadido) {
            JOptionPane.showMessageDialog(this, "No hay ninguna categoría visible. Selecciona una categoría primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Panel.jPanel6.revalidate();
        Panel.jPanel6.repaint();
        
        JOptionPane.showMessageDialog(this, "Producto añadido correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        jTextField1.setText("");
        jTextField2.setText("");
        rutaImagenSeleccionada = null;
        jButton2.setText("Seleccionar imagen");
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Botón SELECCIONAR IMAGEN
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Elige una imagen");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imágenes (.jpg, .png, .jpeg)", "jpg", "png", "jpeg"));

        int resultado = fileChooser.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            rutaImagenSeleccionada = archivoSeleccionado.getAbsolutePath();
            jButton2.setText("Imagen seleccionada");
            jButton2.setForeground(new java.awt.Color(0, 150, 0));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Botón BORRAR producto
        String nombreProducto = jTextField1.getText().trim();
        
        // Validar que no esté vacío
        if (nombreProducto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, escribe el nombre del producto a borrar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Buscar la categoría visible actual
        String categoriaActual = Panel.categoriaActual;
        if (categoriaActual == null || categoriaActual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ninguna categoría seleccionada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Verificar que el producto existe en la estructura de datos
        boolean productoExiste = false;
        if (productoxml.productosPorCategoria.containsKey(categoriaActual)) {
            for (productoxml.ProductoData prod : productoxml.productosPorCategoria.get(categoriaActual)) {
                if (prod.nombre.equals(nombreProducto)) {
                    productoExiste = true;
                    break;
                }
            }
        }
        
        if (!productoExiste) {
            JOptionPane.showMessageDialog(this, "El producto '" + nombreProducto + "' no existe en esta categoría", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirmar antes de borrar
        int respuesta = JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que quieres borrar el producto '" + nombreProducto + "'?",
            "Confirmar borrado",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if (respuesta == JOptionPane.YES_OPTION) {
            // Eliminar de la estructura de datos y del XML (también borra la imagen)
            boolean eliminado = productoxml.eliminarProducto(nombreProducto, categoriaActual);
            
            if (!eliminado) {
                JOptionPane.showMessageDialog(this, "Error al eliminar el producto", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Eliminar del panel visual
            for (int i = 0; i < Panel.jPanel6.getComponentCount(); i++) {
                if (Panel.jPanel6.getComponent(i).isVisible() && Panel.jPanel6.getComponent(i) instanceof PanelCategoria) {
                    PanelCategoria pc = (PanelCategoria) Panel.jPanel6.getComponent(i);
                    
                    // Buscar y eliminar el componente Producto con ese nombre
                    Component[] componentes = pc.jPanel1.getComponents();
                    for (Component comp : componentes) {
                        if (comp instanceof Producto) {
                            Producto producto = (Producto) comp;
                            if (producto.getNombreProducto().equals(nombreProducto)) {
                                pc.jPanel1.remove(producto);
                                break;
                            }
                        }
                    }
                    
                    pc.jPanel1.revalidate();
                    pc.jPanel1.repaint();
                    break;
                }
            }
            
            Panel.jPanel6.revalidate();
            Panel.jPanel6.repaint();
            
            JOptionPane.showMessageDialog(this, "Producto '" + nombreProducto + "' borrado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            jTextField1.setText("");
            jTextField2.setText("");
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

/*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioProducto dialog = new FormularioProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
